// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNvTLRHRBQwUGzILb1O_QKZKcVGL1IEs',
    appId: '1:459211142809:web:57f9cb7278e56835a62a08',
    messagingSenderId: '459211142809',
    projectId: 'moneycare-f7e6b',
    authDomain: 'moneycare-f7e6b.firebaseapp.com',
    storageBucket: 'moneycare-f7e6b.firebasestorage.app',
    measurementId: 'G-0SV1WZZDS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWPPMK73VrGLMN3_WC9z6c-cdMgZ0kl0',
    appId: '1:459211142809:android:498ecae46eee1eb3a62a08',
    messagingSenderId: '459211142809',
    projectId: 'moneycare-f7e6b',
    storageBucket: 'moneycare-f7e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJcWCIGbToH7utPsF6-pU1gDJaakinlrE',
    appId: '1:459211142809:ios:37eb9343ee50420ca62a08',
    messagingSenderId: '459211142809',
    projectId: 'moneycare-f7e6b',
    storageBucket: 'moneycare-f7e6b.firebasestorage.app',
    iosBundleId: 'com.example.doanCn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJcWCIGbToH7utPsF6-pU1gDJaakinlrE',
    appId: '1:459211142809:ios:37eb9343ee50420ca62a08',
    messagingSenderId: '459211142809',
    projectId: 'moneycare-f7e6b',
    storageBucket: 'moneycare-f7e6b.firebasestorage.app',
    iosBundleId: 'com.example.doanCn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCNvTLRHRBQwUGzILb1O_QKZKcVGL1IEs',
    appId: '1:459211142809:web:8e6bcf70284b1756a62a08',
    messagingSenderId: '459211142809',
    projectId: 'moneycare-f7e6b',
    authDomain: 'moneycare-f7e6b.firebaseapp.com',
    storageBucket: 'moneycare-f7e6b.firebasestorage.app',
    measurementId: 'G-Z946Q29ZEK',
  );
}
