const Map<String, String> enUS = {
  // ============ Common ============
  'common.confirm': 'Confirm',
  'common.close': 'Close',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.done': 'Done',
  'common.skip': 'Skip',
  'common.next': 'Next',
  'common.back': 'Back',
  'common.start': 'Get Started',

  'common.apply': 'Apply',
  'common.clearFilter': 'Clear Filter',
  'common.clearAllFilters': 'Clear All Filters',
  'common.noData': 'No data available.',
  'common.loading': 'Loading...',
  'common.retry': 'Retry',
  'common.user': 'User',
  'common.viewDetail': 'View Details',
  'common.all': 'All',
  'common.today': 'Today',
  'common.yesterday': 'Yesterday',

  // ============ Greeting ============
  'greeting.morning': 'Good morning ☀️',
  'greeting.afternoon': 'Good afternoon 🌤️',
  'greeting.evening': 'Good evening 🌙',

  // ============ Snackbar titles ============
  'snackbar.success': 'Success',
  'snackbar.error': 'An error occurred',
  'snackbar.warning': 'Warning',
  'snackbar.info': 'Info',

  // ============ Auth ============
  'auth.login': 'Login',
  'auth.loginSubtitle': 'Please login with your Email.',
  'auth.loginDescription': 'Please login to use Money Care.',
  'auth.loginWithGoogle': 'Login with Google',
  'auth.loginWithFacebook': 'Login with Facebook',
  'auth.signup': 'Sign Up',
  'auth.registerSubtitle': 'Register an account with your Email',
  'auth.noAccount': "Don't have an account? ",
  'auth.alreadyHaveAccount': 'Already have an account? ',
  'auth.firstName': 'First Name',
  'auth.lastName': 'Last Name',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.forgotPasswordTitle': 'Forgot Password',
  'auth.forgotPasswordDescription': 'We will send you an OTP code.',
  'auth.rememberPassword': 'Remember your password? ',
  'auth.logout': 'Logout',

  // ============ OTP ============
  'otp.getOtp': 'Get OTP',
  'otp.enterOtp': 'Enter OTP',
  'otp.description': 'Enter the OTP code to reset your password.',
  'otp.label': 'OTP Code',
  'otp.hint': '- - - - - -',
  'otp.notReceive': "Didn't receive the code? Retry in ",
  'otp.confirmButton': 'Confirm OTP',

  // ============ Reset Password ============
  'resetPassword.title': 'Change Password',
  'resetPassword.description': 'Please enter your new password.',

  // ============ Onboarding ============
  'onboarding.expenseTitle': 'Manage',
  'onboarding.expenseHighlight': 'your finances',
  'onboarding.expenseDescription':
      'Quickly record expenses, clearly categorize and view visual reports to make better financial decisions every day.',
  'onboarding.financialTitle': 'Master',
  'onboarding.financialHighlight': 'your money',
  'onboarding.financialDescription':
      'Smart money management so you always control your income, expenses and savings. Start your journey to financial freedom – take control of your life.',
  'onboarding.incomeTitle': 'What is your monthly income?',
  'onboarding.welcomeTitle': 'Welcome to ',
  'onboarding.welcomeHighlight': 'Money Care',
  'onboarding.welcomeDescription':
      'We provide a solution to help you manage your spending easily and effectively.',

  // ============ Home ============
  'home.title': 'Home',
  'home.recentTransactions': 'Recent Transactions',
  'home.overview': 'Overview',

  'home.monthlySpending': 'This Month Spending',
  'home.monthlySpendingSurvival': 'Essential Spending (Survival)',
  'home.savingPlan': 'Saving Plan',
  'home.savingPlanSubtitle': 'Keep spending under 80% of your limit',
  'home.monthlyIncome': 'This Month Income',
  'home.hiddenNonEssential':
      'Hidden @count non-essential items',
  'home.maxCutSpending': 'This Month Spending (Maximum Cut!)',
  'home.spentInMonth': 'Amount spent this month',
  'home.spentIn7Days': 'Amount spent in the last 7 days',
  'home.balance': 'Balance',

  // ============ Profile / User Center ============
  'profile.title': 'Personal Finance',
  'user.centerTitle': 'Profile',
  'profile.info': 'Personal Info',
  'profile.savingGoals': 'Saving Goals',
  'profile.expiredGoals': 'Expired Goals',
  'profile.categoryManagement': 'Category Management',
  'profile.darkMode': 'Dark Mode',
  'profile.language': 'Language',
  'profile.targetTitle': 'Saving Target',
  'profile.yourProfile': 'Your Profile',
  'profile.avatar': 'Avatar',
  'profile.fixedCosts': 'Fixed Costs',
  'profile.basicInfo': 'Basic Info',
  'profile.financialInfo': 'Financial Info',
  'profile.avatarLink': 'Avatar URL',
  'profile.avatarHint': 'Enter your avatar URL',
  'profile.nameHint': 'e.g., John Doe',
  'profile.lastNameHint': 'e.g., Smith',
  'profile.monthlyIncomeLabel': 'Monthly Income (VND)',
  'profile.monthlyIncomeHint': 'e.g., 15,000,000',
  'profile.incomeDayLabel': 'Monthly Income Day',
  'profile.selectDayHint': 'Select Day',
  'profile.updateSuccess': 'Updated successfully',
  'profile.incomeDayValue': 'Day @day',

  // ============ Statistics ============
  'statistics.title': 'Statistics',
  'statistics.totalMonth': 'Monthly Total Spending',
  'statistics.dailyAverage': 'Daily Average Spending',
  'statistics.monthlyAverage': 'Monthly Average Spending',
  'statistics.limitOverview': 'Spending Overview',
  'statistics.balance': 'Balance',

  'statistics.income': 'Income',
  'statistics.expense': 'Expense',
  'statistics.monthlyIncome': 'Monthly Income',
  'statistics.dailyIncome': 'Daily Income',
  'statistics.monthlyExpense': 'Monthly Expense',
  'statistics.dailyExpense': 'Daily Expense',
  'statistics.incomeOverview': 'Income Overview',
  'statistics.goalStats': 'Saving Goal Statistics',
  'statistics.exportTitle': 'Export Report',
  'statistics.exportEmailNote': 'The report will be sent to your email (@email)',
  'statistics.monthly': 'monthly',
  'statistics.daily': 'daily',

  // ============ Period Comparison ============
  'comparison.title': 'Compare with Previous',
  'comparison.change': 'Change',
  'comparison.income': 'Income',
  'comparison.expense': 'Expense',
  'comparison.balance': 'Balance',
  'comparison.previousMonth': 'Last month',
  'comparison.currentMonth': 'This month',
  'comparison.previousDay': 'Yesterday',
  'comparison.currentDay': 'Today',

  // ============ Transaction ============
  'transaction.title': 'Income - Expense',
  'transaction.expense': 'Expense',
  'transaction.income': 'Income',
  'transaction.photoTitle': 'Photo Record',
  'transaction.scanAi': 'AI Analysis',
  'transaction.scanning': 'Analyzing...',
  'transaction.scanSuccess': 'Information extracted successfully!',
  'transaction.scanError': 'Receipt scan error: ',
  'transaction.scanInvalid':
      'Cannot recognize information. The image may be blurry or not a receipt. Please retake a clear photo!',
  'transaction.unknownMerchant': 'Unknown Merchant',
  'transaction.selectCategory': 'Select Category',
  'transaction.noCategory': 'No categories available',
  'transaction.photoRequired': 'Please take or select a photo for the record.',
  'transaction.userNotFound':
      'Cannot identify user. Please login again.',
  'transaction.createSuccess': 'Photo record created successfully',
  'transaction.photoPreview': 'Transaction Photo',
  'transaction.retakePhoto': 'Retake',
  'transaction.infoSection': 'Record Info',
  'transaction.classificationSection': 'Classification',
  'transaction.incomeNoCategory':
      'Income records do not require a category.',
  'transaction.detail': 'Transaction Detail',
  'transaction.amount': 'Amount',
  'transaction.note': 'Note',
  'transaction.date': 'Date',
  'transaction.category': 'Category',
  'transaction.recurring': 'Recurring Transaction',
  'transaction.noTransactions': 'No matching transactions',
  'transaction.expenseType': 'Expense Item',
  'transaction.incomeType': 'Income Item',
  'transaction.categoryLabel': 'Category',
  'transaction.timeLabel': 'Time',
  'transaction.none': 'None',
  'transaction.noNote': 'No note',
  'transaction.evidencePhoto': 'Evidence Photo',
  'transaction.editExpense': 'Edit Expense',
  'transaction.editIncome': 'Edit Income',
  'transaction.selectTypeDesc': 'Select the transaction type you want to create.',
  'transaction.recordWithPhoto': 'Record with Photo',
  'transaction.recordWithPhotoDesc': 'Take photo, enter amount and save fast',
  'transaction.noRecent': 'No recent transactions found.',
  'transaction.deleteConfirm': 'Are you sure you want to delete this transaction? This action cannot be undone.',
  'transaction.deleteSuccess': 'Transaction deleted successfully',
  'transaction.searchHint': 'Search transactions',
  'transaction.dateLabel': 'Transaction Date',
  'transaction.dateHint': 'Select date',
  'transaction.amountHint': 'Enter amount',
  'transaction.categoryHint': 'Select category',
  'transaction.noCategoryFound': 'No categories found',
  'transaction.noteHint': 'Enter note',
  'transaction.create': 'Create',
  'transaction.update': 'Update',
  'transaction.editTitle': 'Edit Category',
  'transaction.updateSuccess': 'Updated successfully',
  'transaction.selectCategoryTitle': 'Select Category',
  'transaction.categorySurvivalDesc': 'Survival Mode: only essential categories are shown.',
  'transaction.categoryNormalDesc': 'Select an appropriate group for your transaction.',
  'transaction.noCategoryAvailable': 'No categories available.\nPlease check your fund settings.',

  // ============ Filter ============
  'filter.title': 'Transaction Filter',
  'filter.description': 'Choose how to narrow down the transaction list.',
  'filter.dateDescription': 'Select a time range to view transactions more accurately.',
  'filter.categoryDescription': 'Narrow down the transaction list by a category you want to view.',
  'filter.byCategory': 'Filter by Category',
  'filter.byCategorySubtitle': 'Select a specific expense or income type',
  'filter.byTime': 'Filter by Time',
  'filter.activeCount': 'Applying @count filter criteria.',
  'filter.noActive': 'No filters applied.',
  'filter.selectedCategory': 'Selected: @name',
  'filter.selected1Category': 'Selected 1 category',
  'filter.timeToday': 'Today',
  'filter.timeWeek': 'This Week',
  'filter.timeMonth': 'This Month',
  'filter.timeCustom': 'Custom',
  'filter.selectingDate': 'Selected: @label',
  'filter.noDateSelected': 'No time period selected',
  'filter.noCategorySelected': 'No category selected',
  'filter.selected1Type': 'Selected 1 transaction category',

  // ============ Saving Goal ============
  'savingGoal.saved': 'Saved',
  'savingGoal.target': 'Target',
  'savingGoal.transactions': 'Transactions',
  'savingGoal.dailyAverage': 'Avg/day',
  'savingGoal.remaining': 'Remaining',
  'savingGoal.completeEarly': 'Complete Goal Early',

  // ============ Spending Limit ============
  'spending.limit': 'Limit:',
  'spending.spent': 'Spent:',

  // ============ Budget Detail ============
  'budget.detail': 'Budget Detail',
  'budget.monthlyTitle': 'Monthly Budget',
  'budget.totalBudget': 'Total Budget',
  'budget.spent': 'Spent',
  'budget.remaining': 'Remaining',
  'budget.used': 'used',
  'budget.dailyAllowance': 'Daily allowance',
  'budget.daysLeft': 'Days remaining',
  'budget.day': 'day',
  'budget.days': 'days',
  'budget.exceeded': 'Over budget',
  'budget.nearLimit': 'Near limit',
  'budget.onTrack': 'On track',

  // ============ Streak / Calendar ============
  'streak.calendarTitle': 'Achievement Calendar',
  'streak.hasTransaction': 'Has transactions',
  'streak.today': 'Today',
  'streak.mon': 'Mon',
  'streak.tue': 'Tue',
  'streak.wed': 'Wed',
  'streak.thu': 'Thu',
  'streak.fri': 'Fri',
  'streak.sat': 'Sat',
  'streak.sun': 'Sun',
  'streak.selectDayDesc': 'Select a day to view transactions',
  'streak.transactionOnDay': 'Transactions on @day',
  'streak.transactionCount': '@count transactions',
  'streak.noTransactionOnDay': 'No transactions found',

  // ============ Category Management ============
  'categoryMgmt.title': 'Category Management',
  'categoryMgmt.add': 'Add Category',
  'categoryMgmt.edit': 'Edit Category',
  'categoryMgmt.delete': 'Delete Category',

  // ============ Chatbot ============
  'chatbot.title': 'Financial Assistant',
  'chatbot.desc': 'Let the AI assistant help you manage your finances',
  'chatbot.hintText': 'Ask AI anything...',
  'chatbot.analysisTitle': '📊 Spending Analysis',
  'chatbot.analysisDesc': 'Get feedback and saving advice based on actual spending.',
  'chatbot.analysisTemplate': 'Analyze my recent spending and give me saving advice.',
  'chatbot.budgetTitle': '🎯 Budget Suggestions',
  'chatbot.budgetDesc': 'AI will help you plan a smart budget for next month.',
  'chatbot.budgetTemplate': 'Suggest a budget plan based on my spending habits.',
  'chatbot.quickRecordTitle': '📝 Quick Record',
  'chatbot.quickRecordDesc': 'Record fast: "breakfast 35k this morning", "gas 50k"...',
  'chatbot.quickRecordTemplate': 'breakfast 35k today',
  'chatbot.financialAnalysis': 'Financial Analysis',
  'chatbot.transactionSaved': '✅ Transaction recorded successfully!',
  'chatbot.transactionListError': 'Cannot display transaction list.',
  'chatbot.categoryListError': 'Cannot display category list.',
  'chatbot.categoryCreated': '✅ New category created successfully!',
  'chatbot.connectionError': 'Connection error: @error',

  // ============ Notification ============
  'notification.title': 'Notifications',
  'notification.empty': 'You have no notifications.',

  // ============ Dashboard Customization ============
  'dashboard.customizeTitle': 'Customize Dashboard',
  'dashboard.customizeDesc': 'Drag and drop to reorder or hide/show sections',
  'dashboard.section.quickStatus': 'Quick Status (Streak, Finance Mode)',
  'dashboard.section.spendingSummary': 'Income/Expense Summary',
  'dashboard.section.recentTransactions': 'Recent Transactions',
  'dashboard.section.spendingOverview': 'Spending Chart',

  'dashboard.section.monthlySpending': 'Spending by Category',
  'dashboard.section.monthlyIncome': 'Income by Category',
  'dashboard.saveSuccess': 'Dashboard layout updated!',

  // ============ Widget Settings ============
  'widget.settingTitle': 'Widget Settings',
  'widget.showBalance': 'Show balance on Widget',
  'widget.showBalanceDesc': 'Toggle to hide sensitive financial info on the home screen',

  // ============ Report ============
  'report.title': 'Annual Report',
  'report.portfolio': 'Annual Portfolio Report',

  // ============ Recurring Transaction ============
  'recurring.title': 'Recurring Transactions',

  // ============ Premium ============
  'premium.unlock': 'Unlock Premium',

  // ============ Language ============
  'language.vietnamese': 'Tiếng Việt',
  'language.english': 'English',
  'language.title': 'Select Language',
};
