const Map<String, String> viVN = {
  // ============ Common ============
  'common.confirm': 'Xác nhận',
  'common.close': 'Đóng',
  'common.cancel': 'Hủy',
  'common.save': 'Lưu',
  'common.delete': 'Xóa',
  'common.edit': 'Sửa',
  'common.done': 'Hoàn tất',
  'common.skip': 'Bỏ qua',
  'common.next': 'Tiếp tục',
  'common.back': 'Quay lại',
  'common.close': 'Đóng',
  'common.start': 'Bắt đầu',
  'common.apply': 'Áp dụng',
  'common.clearFilter': 'Xóa lọc',
  'common.clearAllFilters': 'Xóa tất cả bộ lọc',
  'common.noData': 'Không có dữ liệu nào.',
  'common.loading': 'Đang tải...',
  'common.retry': 'Thử lại',
  'common.user': 'Người dùng',
  'common.viewDetail': 'Xem chi tiết',
  'common.all': 'Tất cả',
  'common.today': 'Hôm nay',
  'common.yesterday': 'Hôm qua',

  // ============ Greeting ============
  'greeting.morning': 'Chào buổi sáng ☀️',
  'greeting.afternoon': 'Chào buổi chiều 🌤️',
  'greeting.evening': 'Chào buổi tối 🌙',

  // ============ Snackbar titles ============
  'snackbar.success': 'Thành công',
  'snackbar.error': 'Có lỗi xảy ra',
  'snackbar.warning': 'Lưu ý',
  'snackbar.info': 'Thông báo',

  // ============ Auth ============
  'auth.login': 'Đăng nhập',
  'auth.loginSubtitle': 'Vui lòng đăng nhập với Email của bạn.',
  'auth.loginDescription': 'Vui lòng đăng nhập để sử dụng Money Care.',
  'auth.loginWithGoogle': 'Đăng nhập với Google',
  'auth.loginWithFacebook': 'Đăng nhập với Facebook',
  'auth.signup': 'Đăng ký',
  'auth.registerSubtitle': 'Đăng ký tài khoản với Email của bạn',
  'auth.noAccount': 'Bạn chưa có tài khoản? ',
  'auth.alreadyHaveAccount': 'Bạn đã có tài khoản? ',
  'auth.firstName': 'Họ',
  'auth.lastName': 'Tên',
  'auth.email': 'Email',
  'auth.password': 'Mật khẩu',
  'auth.confirmPassword': 'Nhập lại mật khẩu',
  'auth.forgotPassword': 'Quên mật khẩu?',
  'auth.forgotPasswordTitle': 'Quên mật khẩu',
  'auth.forgotPasswordDescription': 'Chúng tôi sẽ gửi cho bạn mã OTP.',
  'auth.rememberPassword': 'Nhớ mật khẩu? ',
  'auth.logout': 'Đăng xuất',

  // ============ OTP ============
  'otp.getOtp': 'Nhận mã OTP',
  'otp.enterOtp': 'Nhập mã OTP',
  'otp.description': 'Nhập mã OTP để lấy lại mật khẩu.',
  'otp.label': 'Mã OTP',
  'otp.hint': '- - - - - -',
  'otp.notReceive': 'Không nhận được mã? Thử lại sau ',
  'otp.confirmButton': 'Xác nhận mã OTP',

  // ============ Reset Password ============
  'resetPassword.title': 'Thay đổi mật khẩu',
  'resetPassword.description': 'Vui lòng nhập mật khẩu mới của bạn.',

  // ============ Onboarding ============
  'onboarding.expenseTitle': 'Quản lý',
  'onboarding.expenseHighlight': 'thu chi',
  'onboarding.expenseDescription':
      'Ghi chép chi tiêu nhanh chóng, phân loại rõ ràng và xem báo cáo trực quan để đưa ra quyết định tài chính tốt hơn mỗi ngày.',
  'onboarding.financialTitle': 'Làm chủ',
  'onboarding.financialHighlight': 'tài chính',
  'onboarding.financialDescription':
      'Quản lý tiền bạc thông minh để bạn luôn kiểm soát được thu nhập, chi tiêu và tiết kiệm. Bắt đầu hành trình làm chủ tài chính – làm chủ cuộc sống của chính mình.',
  'onboarding.incomeTitle': 'Số tiền thu nhập hàng tháng của bạn là bao nhiêu?',
  'onboarding.welcomeTitle': 'Chào mừng bạn đến với ',
  'onboarding.welcomeHighlight': 'Money Care',
  'onboarding.welcomeDescription':
      'Chúng tôi đem đến giải pháp giúp bạn quản lý chi tiêu cực kỳ dễ dàng và hiệu quả.',

  // ============ Home ============
  'home.recentTransactions': 'Giao dịch gần đây',
  'home.overview': 'Tổng quan',
  'home.spendingLimit': 'Hạn mức chi tiêu',
  'home.monthlySpending': 'Chi tiêu tháng này',
  'home.monthlySpendingSurvival': 'Chi tiêu thiết yếu (Sinh tồn)',
  'home.savingPlan': 'Kế hoạch tiết kiệm',
  'home.savingPlanSubtitle': 'Duy trì chi tiêu dưới 80% hạn mức',
  'home.monthlyIncome': 'Thu nhập tháng này',
  'home.hiddenNonEssential':
      'Đã ẩn @count mục không thiết yếu',
  'home.maxCutSpending': 'Chi tiêu tháng này (Cắt giảm tối đa!)',
  'home.spentInMonth': 'Số tiền bạn chi trong tháng',
  'home.spentIn7Days': 'Số tiền đã chi tiêu trong 7 ngày gần đây',
  'home.balance': 'Số dư',

  // ============ Profile / User Center ============
  'profile.title': 'Tài chính cá nhân',
  'profile.info': 'Thông tin cá nhân',
  'profile.savingGoals': 'Quỹ tiết kiệm',
  'profile.expiredGoals': 'Mục tiêu đã hết hạn',
  'profile.categoryManagement': 'Quản lý danh mục',
  'profile.darkMode': 'Chế độ tối',
  'profile.language': 'Ngôn ngữ',
  'profile.targetTitle': 'Mục tiêu tiết kiệm',
  'profile.yourProfile': 'Hồ sơ của bạn',
  'profile.avatar': 'Ảnh đại diện',
  'profile.fixedCosts': 'Chi phí cố định',
  'profile.basicInfo': 'Thông tin cơ bản',
  'profile.financialInfo': 'Thông tin tài chính',
  'profile.avatarLink': 'Link ảnh đại diện',
  'profile.avatarHint': 'Nhập URL ảnh của bạn',
  'profile.nameHint': 'VD: Văn A',
  'profile.lastNameHint': 'VD: Nguyễn',
  'profile.monthlyIncomeLabel': 'Thu nhập hàng tháng (VNĐ)',
  'profile.incomeDayLabel': 'Ngày nhận tiền hàng tháng',
  'profile.selectDayHint': 'Chọn ngày',
  'profile.updateSuccess': 'Cập nhật thành công',
  'profile.incomeDayValue': 'Ngày @day',

  // ============ Statistics ============
  'statistics.title': 'Thống kê',
  'statistics.totalMonth': 'Tổng chi tiêu theo tháng',
  'statistics.dailyAverage': 'Trung bình chi tiêu theo ngày',
  'statistics.monthlyAverage': 'Trung bình chi tiêu theo tháng',
  'statistics.limitOverview': 'Tổng quan chi tiêu',
  'statistics.title': 'Thống kê',
  'statistics.balance': 'Số dư',
  'statistics.income': 'Thu',
  'statistics.expense': 'Chi',
  'statistics.monthlyIncome': 'Thu nhập theo tháng',
  'statistics.dailyIncome': 'Thu nhập theo ngày',
  'statistics.monthlyExpense': 'Chi tiêu theo tháng',
  'statistics.dailyExpense': 'Chi tiêu theo ngày',
  'statistics.incomeOverview': 'Tổng quan thu nhập',
  'statistics.goalStats': 'Thống kê mục tiêu tiết kiệm',
  'statistics.exportTitle': 'Xuất báo cáo',
  'statistics.exportEmailNote': 'Báo cáo sẽ được gửi về email của bạn (@email)',
  'statistics.monthly': 'hàng tháng',
  'statistics.daily': 'hàng ngày',

  // ============ Period Comparison ============
  'comparison.title': 'So sánh với kỳ trước',
  'comparison.change': 'Thay đổi',
  'comparison.income': 'Thu nhập',
  'comparison.expense': 'Chi tiêu',
  'comparison.balance': 'Số dư',
  'comparison.previousMonth': 'Tháng trước',
  'comparison.currentMonth': 'Tháng này',
  'comparison.previousDay': 'Hôm qua',
  'comparison.currentDay': 'Hôm nay',

  // ============ Transaction ============
  'transaction.title': 'Thu - Chi',
  'transaction.expense': 'Chi',
  'transaction.income': 'Thu',
  'transaction.photoTitle': 'Bản ghi kèm ảnh',
  'transaction.scanAi': 'Phân tích AI',
  'transaction.scanning': 'Đang phân tích...',
  'transaction.scanSuccess': 'Đã trích xuất thông tin thành công!',
  'transaction.scanError': 'Lỗi quét hóa đơn: ',
  'transaction.scanInvalid':
      'Không thể nhận diện thông tin. Ảnh có thể bị mờ hoặc không phải hóa đơn. Bạn vui lòng chụp lại rõ nét nhé!',
  'transaction.unknownMerchant': 'Cửa hàng không xác định',
  'transaction.selectCategory': 'Chọn category',
  'transaction.noCategory': 'Không có category để lựa chọn',
  'transaction.photoRequired': 'Vui lòng chụp hoặc chọn ảnh cho bản ghi.',
  'transaction.userNotFound':
      'Không thể xác định người dùng. Vui lòng đăng nhập lại.',
  'transaction.createSuccess': 'Tạo bản ghi kèm ảnh thành công',
  'transaction.photoPreview': 'Ảnh giao dịch',
  'transaction.retakePhoto': 'Chụp lại',
  'transaction.infoSection': 'Thông tin bản ghi',
  'transaction.classificationSection': 'Phân loại',
  'transaction.incomeNoCategory':
      'Bản ghi thu hiện không yêu cầu category.',
  'transaction.detail': 'Chi tiết giao dịch',
  'transaction.amount': 'Số tiền',
  'transaction.note': 'Ghi chú',
  'transaction.date': 'Ngày',
  'transaction.category': 'Phân loại',
  'transaction.recurring': 'Giao dịch định kỳ',
  'transaction.noTransactions': 'Không có giao dịch phù hợp',
  'transaction.expenseType': 'Khoản chi tiêu',
  'transaction.incomeType': 'Khoản thu nhập',
  'transaction.categoryLabel': 'Hạng mục',
  'transaction.timeLabel': 'Thời gian',
  'transaction.none': 'Không có',
  'transaction.noNote': 'Không có ghi chú',
  'transaction.evidencePhoto': 'Hình ảnh minh chứng',
  'transaction.editExpense': 'Chỉnh sửa chi',
  'transaction.editIncome': 'Chỉnh sửa thu',
  'transaction.selectTypeDesc': 'Chọn loại giao dịch bạn muốn tạo mới.',
  'transaction.recordWithPhoto': 'Bản ghi kèm ảnh',
  'transaction.recordWithPhotoDesc': 'Chụp ảnh, nhập số tiền và lưu giao dịch nhanh',
  'transaction.noRecent': 'Không có giao dịch nào gần đây.',
  'transaction.deleteConfirm': 'Bạn có chắc chắn muốn xóa giao dịch này? Hành động này không thể hoàn tác.',
  'transaction.deleteSuccess': 'Đã xóa giao dịch thành công',
  'transaction.searchHint': 'Tìm giao dịch',
  'transaction.dateLabel': 'Ngày giao dịch',
  'transaction.dateHint': 'Chọn ngày',
  'transaction.amountHint': 'Nhập số tiền',
  'transaction.categoryHint': 'Chọn phân loại',
  'transaction.noCategoryFound': 'Chưa có danh mục nào',
  'transaction.noteHint': 'Nhập ghi chú',
  'transaction.create': 'Tạo',
  'transaction.update': 'Cập nhật',
  'transaction.editTitle': 'Chỉnh sửa phân loại',
  'transaction.updateSuccess': 'Chỉnh sửa thành công',

  // ============ Filter ============
  'filter.title': 'Bộ lọc giao dịch',
  'filter.description': 'Chọn cách bạn muốn thu hẹp danh sách giao dịch.',
  'filter.dateDescription': 'Chọn mốc thời gian phù hợp để xem giao dịch chính xác hơn.',
  'filter.categoryDescription': 'Thu hẹp danh sách giao dịch theo phân loại bạn muốn xem.',
  'filter.byCategory': 'Lọc theo phân loại',
  'filter.byCategorySubtitle': 'Chọn loại chi tiêu hoặc thu nhập cụ thể',
  'filter.byTime': 'Lọc theo thời gian',
  'filter.activeCount': 'Đang áp dụng @count tiêu chí lọc.',
  'filter.noActive': 'Chưa có bộ lọc nào được áp dụng.',
  'filter.selectedCategory': 'Đã chọn: @name',
  'filter.selected1Category': 'Đã chọn 1 phân loại',
  'filter.timeToday': 'Hôm nay',
  'filter.timeWeek': 'Tuần này',
  'filter.timeMonth': 'Tháng này',
  'filter.timeCustom': 'Tùy chỉnh',
  'filter.selectingDate': 'Đang chọn: @label',
  'filter.noDateSelected': 'Chưa chọn khoảng thời gian',
  'filter.noCategorySelected': 'Chưa chọn phân loại nào',
  'filter.selected1Type': 'Đã chọn 1 phân loại giao dịch',

  // ============ Saving Goal ============
  'savingGoal.saved': 'Đã tiết kiệm',
  'savingGoal.target': 'Mục tiêu',
  'savingGoal.transactions': 'Giao dịch',
  'savingGoal.dailyAverage': 'TB/ngày',
  'savingGoal.remaining': 'Còn lại',
  'savingGoal.completeEarly': 'Hoàn thành sớm mục tiêu',

  // ============ Spending Limit ============
  'spending.limit': 'Hạn mức:',
  'spending.spent': 'Đã tiêu:',

  // ============ Budget Detail ============
  'budget.detail': 'Chi tiết ngân sách',
  'budget.monthlyTitle': 'Ngân sách tháng',
  'budget.totalBudget': 'Tổng ngân sách',
  'budget.spent': 'Đã chi',
  'budget.remaining': 'Còn lại',
  'budget.used': 'đã dùng',
  'budget.dailyAllowance': 'Khả dụng mỗi ngày',
  'budget.daysLeft': 'Số ngày còn lại',
  'budget.day': 'ngày',
  'budget.days': 'ngày',
  'budget.exceeded': 'Vượt ngân sách',
  'budget.nearLimit': 'Sắp hết',
  'budget.onTrack': 'Đang tốt',

  // ============ Streak / Calendar ============
  'streak.calendarTitle': 'Lịch Thành Tích',
  'streak.hasTransaction': 'Có giao dịch',
  'streak.today': 'Hôm nay',

  // ============ Category Management ============
  'categoryMgmt.title': 'Quản lý danh mục',
  'categoryMgmt.add': 'Thêm danh mục',
  'categoryMgmt.edit': 'Sửa danh mục',
  'categoryMgmt.delete': 'Xóa danh mục',

  // ============ Chatbot ============
  'chatbot.title': 'Trợ lý tài chính',
  'chatbot.desc': 'Nhờ trợ lý AI giúp bạn quản lý tài chính',
  'chatbot.hintText': 'Hỏi AI bất cứ điều gì...',
  'chatbot.analysisTitle': '📊 Phân tích chi tiêu',
  'chatbot.analysisDesc': 'Nhận nhận xét và lời khuyên tiết kiệm dựa trên chi tiêu thực tế.',
  'chatbot.analysisTemplate': 'Phân tích chi tiêu gần đây của tôi và cho tôi lời khuyên tiết kiệm.',
  'chatbot.budgetTitle': '🎯 Gợi ý ngân sách',
  'chatbot.budgetDesc': 'AI sẽ giúp bạn lên kế hoạch ngân sách thông minh cho tháng tới.',
  'chatbot.budgetTemplate': 'Hãy gợi ý cho tôi một kế hoạch ngân sách dựa trên thói quen chi tiêu của tôi.',
  'chatbot.quickRecordTitle': '📝 Ghi nhanh chi tiêu',
  'chatbot.quickRecordDesc': 'Ghi chép cực nhanh: "bún bò 35k sáng nay", "đổ xăng 50k"...',
  'chatbot.quickRecordTemplate': 'ăn sáng 35k hôm nay',
  'chatbot.financialAnalysis': 'Phân tích tài chính',
  'chatbot.transactionSaved': '✅ Đã ghi nhận giao dịch thành công!',
  'chatbot.transactionListError': 'Không thể hiển thị danh sách giao dịch.',
  'chatbot.categoryListError': 'Không thể hiển thị danh sách hạng mục.',
  'chatbot.categoryCreated': '✅ Đã tạo hạng mục mới thành công!',
  'chatbot.connectionError': 'Lỗi kết nối: @error',

  // ============ Notification ============
  'notification.title': 'Thông báo',
  'notification.empty': 'Bạn chưa có thông báo nào.',

  // ============ Dashboard Customization ============
  'dashboard.customizeTitle': 'Tùy chỉnh Dashboard',
  'dashboard.customizeDesc': 'Kéo thả để sắp xếp hoặc ẩn/hiện các mục',
  'dashboard.section.quickStatus': 'Trạng thái nhanh (Chuỗi ngày, Chế độ tài chính)',
  'dashboard.section.spendingSummary': 'Tổng quan Thu/Chi',
  'dashboard.section.recentTransactions': 'Giao dịch gần đây',
  'dashboard.section.spendingOverview': 'Biểu đồ chi tiêu',
  'dashboard.section.spendingLimit': 'Hạn mức chi tiêu',
  'dashboard.section.monthlySpending': 'Chi tiêu theo danh mục',
  'dashboard.section.monthlyIncome': 'Thu nhập theo danh mục',
  'dashboard.saveSuccess': 'Đã cập nhật giao diện Dashboard!',

  // ============ Report ============
  'report.title': 'Báo cáo trong năm',
  'report.portfolio': 'Báo cáo danh mục trong năm',

  // ============ Recurring Transaction ============
  'recurring.title': 'Giao dịch định kỳ',

  // ============ Premium ============
  'premium.unlock': 'Mở khóa Premium',

  // ============ Language ============
  'language.vietnamese': 'Tiếng Việt',
  'language.english': 'English',
  'language.title': 'Chọn ngôn ngữ',
};
